application: unfollow-io
version: 1
module: default

instance_class: B1
basic_scaling:
  max_instances: 1
  idle_timeout: 5m

runtime: go
api_version: go1

inbound_services:
- warmup

includes:
- app.yaml
